# Generated by Django 5.2.4 on 2025-07-13 04:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blogmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='img/')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField()),
                ('category', models.CharField()),
                ('dateandtime', models.DateTimeField(default=datetime.datetime(2025, 7, 13, 9, 41, 16, 604340))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
