# Generated by Django 5.2.4 on 2025-07-13 05:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_dateandtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 13, 11, 28, 36, 981372)),
        ),
        migrations.CreateModel(
            name='commentmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField()),
                ('dateandtime', models.DateTimeField(default=datetime.datetime(2025, 7, 13, 11, 28, 36, 981372))),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
