# Generated by Django 5.2.4 on 2025-07-14 15:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogmodel_dateandtime_commentmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 21, 29, 32, 298699)),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 21, 29, 32, 299700)),
        ),
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
