# Generated by Django 5.2.4 on 2025-07-15 06:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogmodel_dateandtime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 11, 55, 57, 828354)),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 11, 55, 57, 829355)),
        ),
        migrations.CreateModel(
            name='likemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'blog')},
            },
        ),
    ]
