# Generated by Django 5.2.4 on 2025-07-18 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogmodel_category_alter_blogmodel_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 9, 14, 44, 922602)),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 9, 14, 44, 923602)),
        ),
    ]
