# Generated by Django 5.2.4 on 2025-07-18 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogmodel_dateandtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 9, 22, 58, 63333)),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 9, 22, 58, 64334)),
        ),
    ]
